controller: {
    KP_x: 0.33,
    KI_x: 0.05,
    KD_x: 0.25,
    X_limit: 0.5,
    
    KP_y: 0.3,
    KI_y: 0.05,
    KD_y: 0.2,
    Y_limit: 0.5,
    
    KP_z: 0.14,
    KI_z: 0.05,
    KD_z: 0.10,
    Z_limit: 0.5,
    
    KP_yaw: 0.1,
    KI_yaw: 0.05,
    KD_yaw: 0.05,
    
    TAKEOFF_HEIGHT: 0.05,
    TAKEOFF_THROTTLE: 0.43,
    TAKEOFF_THROTTLE_TIME: 0.6,
    LAND_TIME: 5.0,
    
    Yaw: 0,
    Flip: 100
}
